name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Proxy Server Docker Image
      run: docker build . --file Dockerfile --tag golang-proxy-server:$(date +%s)
